name: Sync with Original Repository

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.name "Akshay-1824"
          git config --global user.email "deoreakshay180499@gmail.com"

      - name: Fetch changes from original repository
        run: |
          # Add the original repository as a remote
          git remote add upstream https://github.com/Akshay-1804/Simple-CI-CD.git
          # Fetch changes from the original repository
          git fetch upstream
          # Merge changes from the original repository's main branch into the current branch
          git merge upstream/main --no-edit

      - name: Push changes to forked repository
        run: |
          # Push changes to the forked repository's main branch
          git push origin main
        env:
            # Use the GitHub token to authenticate for pushing changes
            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
