# .github/workflows/ci-cd.yml
# name: CI/CD Pipeline

# on:
#   push:
#     branches:
#       - main

# jobs:
# #   build:
# #     runs-on: ubuntu-latest

#      steps:
    #   - name: Checkout code
    #     uses: actions/checkout@v2

    #   - name: Install Node.js
    #     uses: actions/setup-node@v2
    #     with:
    #       node-version: '14'

    #    - name: Install dependencies
    #     run: npm install

    #   - name: Deploy to server
    #     run: |
    #       # Stop the existing server
    #       pm2 stop index.js || true
          
    #       # Start the server
    #       pm2 start index.js --name "my-express-app"

    #       # Wait for server to start
    #       sleep 3


# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Install Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: '14'

#       - name: Install dependencies
#         run: npm install

#       - name: Start server
#         run: node index.js

# .github/workflows/ci-cd.yml

name: Sync with Original Repository

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.name "Akshay-1824"
          git config --global user.email "deoreakshay180499@gmail.com"

      - name: Fetch changes from original repository
        run: |
          git remote add upstream https://github.com/Akshay-1804/Simple-CI-CD.git
          git fetch upstream
          git merge upstream/main --no-edit

      - name: Push changes to forked repository
        run: |
          git push origin main
        env:
            GITHUB_TOKEN: ${{ secrets.my_key }}
