name: Reflect Changes

on:
  [push]

jobs:
  reflect_changes:
    runs-on: windows-latest
    
    steps:
      - name: Checkout original repo
        uses: actions/checkout@v2
        
      - name: Clone repository
        run: |
          cd D:\a\_temp\3cb2526f-954a-45f3-af3b-7f366b868060.ps1:2
          git pull origin main