# .github/workflows/ci-cd.yml
name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
<<<<<<< HEAD
    runs-on: http://localhost:3000/
=======
    runs-on: ubuntu-latest
>>>>>>> 6e233a43611b6f932f1562b1fe47c133aefd663e

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

<<<<<<< HEAD
=======
      - name: Run tests (if any)
        run: npm test  # Add test script in package.json if needed

>>>>>>> 6e233a43611b6f932f1562b1fe47c133aefd663e
      - name: Deploy to server
        run: |
          # Stop the existing server
          pm2 stop index.js || true
          
          # Start the server
          pm2 start index.js --name "my-express-app"

          # Wait for server to start
<<<<<<< HEAD
          sleep 3
=======
          sleep 3
>>>>>>> 6e233a43611b6f932f1562b1fe47c133aefd663e
