name: Reflect Changes

on:
  push:
    branches:
      - main

jobs:
  reflect_changes:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout original repo
        uses: actions/checkout@v2
        
      - name: Clone repository
        run: |
          git clone https://github.com/Akshay-1804/cloned-repo.git
          cd cloned-repo
          git pull origin main
