name: Reflect Changes

on:
  [push]

jobs:
  reflect_changes:
    runs-on: windows-latest
    
    steps:
      - name: Checkout original repo
        uses: actions/checkout@v2
        
      - name: Clone repository
        run: |
          cd D:\Simple-CI-CD
          git pull origin main