name: Reflect Changes

on:
  push:
    branches:
      - main

jobs:
  reflect_changes:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout original repo
        uses: actions/checkout@v2
        
      - name: Pull changes in cloned repo
        run: |
          cd https://github.com/Akshay-1804/cloned-repo.git
          git pull origin main
